
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook
  namespace: example1
  annotations:
    cert-manager.io/inject-ca-from: example1/serving-certificate
  labels:
    app: webhook
webhooks:
  - name: mutate-pods-deployments.example.com
    clientConfig:
      service:
        name: webhook-service
        namespace: example1
        path: /mutate
        port: 8080
    rules:
      - operations:
          - CREATE
        apiGroups:
          - ""
        apiVersions:
          - v1
        resources:
          - pods
      - operations:
          - CREATE
        apiGroups:
          - apps
        apiVersions:
          - v1
        resources:
          - deployments
    admissionReviewVersions:
      - v1
    sideEffects: None
