apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-deployment
  namespace: example1
  labels:
    app: webhook
  annotations:
    cert-manager.io/inject-ca-from: example1/webhook1-certificate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
        - name: webhook
          image: 10.100.102.18:31855/webhook:v1.0.0
          imagePullPolicy: Always
          env:
            - name: DEFAULT_CPU_REQUEST
              value: "500m"
            - name: DEFAULT_MEMORY_REQUEST
              value: "512Mi"
            - name: DEFAULT_CPU_LIMIT
              value: "1000m"
            - name: DEFAULT_MEMORY_LIMIT
              value: "1Gi"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: certs
              mountPath: /etc/ssl/certs
              readOnly: true
      volumes:
        - name: certs
          secret:
            secretName: serving-certificate
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: example1
spec:
  selector:
    app: webhook
  ports:
    - port: 8080
      targetPort: 8080